# -*- coding: utf-8 -*-
"""housing_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rs-Y7m6sgGr4TE5z1ZXLfXuZLbnKGYHH
"""

from google.colab import files  # Upload your CSV 
uploaded = files.upload()


import pandas as pd # Load data 
import numpy as np

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
df.columns = df.columns.str.strip()

print("✅ Data loaded successfully!")


features = ['Rooms', 'Distance', 'Bathroom', 'Car', 'Landsize', # Select columns 
            'BuildingArea', 'YearBuilt', 'Regionname',
            'Type', 'Propertycount']
target = 'Price'

df = df[features + [target]]
df = df.dropna(subset=[target])


numeric_cols = ['Rooms', 'Distance', 'Bathroom', 'Car', 'Landsize', # Clean the data 
                 'BuildingArea', 'YearBuilt', 'Propertycount']

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

df['Regionname'] = df['Regionname'].fillna(df['Regionname'].mode()[0])
df['Type'] = df['Type'].fillna(df['Type'].mode()[0])

df = pd.get_dummies(df, columns=['Regionname', 'Type'], drop_first=True)

print("✅ Data cleaned!")


X = df.drop(target, axis=1) # Split features/target 
y = df[target]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


from sklearn.linear_model import LinearRegression # Train models 
from sklearn.ensemble import RandomForestRegressor

lr = LinearRegression()
lr.fit(X_train, y_train)

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

def evaluate_model(name, model, X_test, y_test):
    predictions = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    print(f"\n📊 {name}")
    print(f"   RMSE: ${rmse:,.0f}")
    print(f"   MAE:  ${mae:,.0f}")
    print(f"   R²:   {r2:.3f}")

    return {'rmse': float(rmse), 'mae': float(mae), 'r2': float(r2)}

lr_metrics = evaluate_model("Linear Regression", lr, X_test, y_test)
rf_metrics = evaluate_model("Random Forest", rf, X_test, y_test)

print("✅ Model training complete!")


import joblib # Save models to disk (with reference columns) 

joblib.dump({'model': lr, 'columns': X.columns, 'metrics': lr_metrics}, 'linear_regression_model.joblib')
joblib.dump({'model': rf, 'columns': X.columns, 'metrics': rf_metrics}, 'random_forest_model.joblib')
print("✅ Models saved!")

files.download('linear_regression_model.joblib') # Download to PC 
files.download('random_forest_model.joblib')